### ISSUE TITLE
Uncaught DivisionByZeroError from get_cart_item_from_session function

### ISSUE THREAD

**Issue by plaidpowered** [Automattic/woocommerce-subscriptions-core#116]
## Describe the bug
On WC Subscriptions 4.0.2 + WC 6.2, a DivideByZero fatal error is thrown when the user's session cart has been set to zero.

## To Reproduce

I don't know exactly how to reproduce the problem, my client reported the WordPress critical error of death screen, I investigated, and found this error in the logs. It gets thrown after she attempts to log in.

```
PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /.../wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-cart-renewal.php:447
Stack trace:
#0 /.../wp-includes/class-wp-hook.php(307): WCS_Cart_Renewal->get_cart_item_from_session()
#1 /.../wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /.../wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(161): apply_filters()
#3 /.../wp-includes/class-wp-hook.php(307): WC_Cart_Session->get_cart_from_session()
#4 /.../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /.../wp-includes/plugin.php(474): WP_Hook->do_action()
#6 /.../wp-settings.php(609): do_action()
#7 /.../wp-config.php(95): require_once('/home/643317.cl...')
#8 /.../wp-load.php(55): require_once('/home/643317.cl...')
#9 /.../wp-blog-header.php(13): require_once('/home/643317.cl...')
#10 /.../index.php(17): require('/home/643317.cl...')
#11 {main}
  thrown in /.../wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-cart-renewal.php on line 447
```

Somehow my client, who is a superadmin on this multisite network, ended up with a cart line item of zero. I suspect it may be related to switching back and forth between sites.

### Expected behavior

It shouldn't throw that error

### Actual behavior

It throws that error

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes
- [ ] Does this issue affect WooCommerce Payments? unknown

## Additional context

To fix this temporarily, I added a sanity check to the `get_cart_item_from_session` function:

From WC 4.0.2, the line number was 428, where I added -

```
if ( empty( $item_to_renew['qty'] ) || $item_to_renew['qty'] < 1 ) {
	return null;
}
```

I realize that the second IF condition is overkill, but I've had weird behavior with `empty` before, so I usually make redundant checks like this.

**Comment by noplanman** [comment]
This is still an issue with WC Subscriptions 4.3.0.

**Comment by noplanman** [comment]
@plaidpowered Would you mind sharing where you added your code snippet?

I'm totally new to WooCommerce, thanks!

**Comment by plaidpowered** [comment]
@noplanman The file was `woocommerce-subscriptions/includes/class-wcs-cart-renewal.php` and line 428 in version 4.0.2, but it looks like things have moved around. Here is an appropriate place in the current version -

https://github.com/Automattic/woocommerce-subscriptions-core/blob/6b8c650c06d92eb1cb2bdb79e3e98aec14920414/includes/class-wcs-cart-renewal.php#L436

As you are new to WooCommerce, keep in mind that editing plugins that are regularly updated can be problematic. As soon as an update happens, your code change will be wiped out. So you'll have to stay on top of it.

**Comment by noplanman** [comment]
Great, thanks @plaidpowered :pray: 

Do you know what chain of events causes this exception to be thrown?
I only get it very rarely and haven't figured out what makes it happen.

**Comment by plaidpowered** [comment]
I could never reproduce it, my client reported it and I caught it in the debug.log, my only theory was that since WooCommerce was running on multiple subdomains, possibly the cart session was set to zero while navigating between these. But I couldn't confirm that.

**Comment by noplanman** [comment]
This seems to be connected with WP cron, as far as I can tell.
The error hits and then I get a failed cron job and a message in WP Admin about a failure when processing a subscription renewal.

The cron event is `woocommerce_scheduled_subscription_payment` and the arguments `'subscription_id' => 12345`
(`12345` being the ID of the sub of course)

I'll apply your patch and see if that takes care of these failures.

Again, I really urge the maintainers here to check this out, as it's definitely some bug somewhere.

**Comment by haszari** [comment]
@noplanman @plaidpowered thank you for reporting and investigating this! The first step is to confirm how to reproduce this, if we can't reproduce we can't prioritise a fix. 

If there's something unusual on these sites then it's a good thing to have the fatal – adding defensive code to silence it might mask a root cause with site data (perhaps).

**Comment by barryhughes** [comment]
Subscriptions Core has now been archived. For more information, please [refer to this announcement](https://developer.woocommerce.com/2025/05/06/developer-advisory-subscriptions-core-code-moving-into-woocommerce-subscriptions-plugin/).
