### ISSUE TITLE
Refactor `wcs_get_subscription()` to not use Order Factory (Unable to purchase subscription with COT enabled)

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#186]
> **Warning** - This issue may not need to be implemented.
> Now that we are going to support/migrate Subscriptions over COT/HPOS tables, the Order Factory should work as we expect it to and so we no longer need to refactory this function.
>
> Once we have implemented a HPOS Subscriptions datastore class and updated `wcs_create_subscription()` to create subscriptions via this datastore when HPOS is enabled, we will need to confirm whether we still need to fix this issue. I suspect we won't

---

## Describe the bug

This issue was discovered by trying to purchase a subscription when custom order tables is enabled on a store. But this is only one of many issues caused by this problem.

Error received:
```
2022-08-02T05:40:06+00:00 CRITICAL Uncaught Error: Call to a member function get_items() on bool in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-synchroniser.php:1148
Stack trace:
#0 /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-includes/class-wp-hook.php(309): WC_Subscriptions_Synchroniser::maybe_add_subscription_meta(1170)
#1 /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#2 /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-includes/post.php(4673): do_action('save_post', 1170, Object(WP_Post), false)
#4 /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/wcs-functions.php(180): wp_insert_post(Array, true)
#5 /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-c in /srv/users/usereaea7e7b/apps/usereaea7e7b/public/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-synchroniser.php on line 1148
```

When a store has custom order tables turned on, the underlying Order Data Store switches over to using the new `OrdersTableDataStore`.

Inside our `wcs_get_subscription()` function we're using the Order Factory to get the subscription object which has worked up until now because Subscriptions are just custom order types. With Subscriptions staying in the WP Posts table, we cant use the Order Factory or any order getters/queries to fetch a subscription.

## To Reproduce

1. Checkout the latest WooCommerce cot-branch and build it
2. Enable the COT feature by using the following custom code:
```
function enable_cot(){
   $order_controller = wc_get_container()
       ->get('Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController');
   if( isset( $order_controller ) ) {
       $order_controller->show_feature();
   }
}
add_action( 'init', 'enable_cot', 99 );
```
4. Go into **WooCommerce > Status > Tools** and run the Create Order Tables tool
5. Go into **WooCommerce > Settings > Advanced > Custom Data Stores**
6. Make sure "Use the WooCommerce orders tables" is enabled
   1. You will need to sync order data to custom tables to enabled this the first time by checking  "Keep the posts table and the orders tables synchronized"
7. Try to purchase a subscription on the checkout

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by mattallan** [comment]
The changes in #189 fix this issue so I'm going to drop the priority to high because I still think we should aim to remove the Order Factory usage in our `wcs_get_subscriptions()`.

Our options are to:
 1. Introduce a new Subscription Factory class similar to the order factory and call a new `Subscription_Factory->get_subscription()` function
 2. Extract the code from `Order_Factory::get_order()` and put in our `wcs_get_subscription()`

I started looking at this before moving onto #189 and I ended up going with option 2 and had the following code:

```
function wcs_get_subscription( $the_subscription ) {
	$subscription = false;

	if ( is_object( $the_subscription ) && wcs_is_subscription( $the_subscription ) ) {
		$the_subscription = $the_subscription->get_id();
	}

	$subscription_type      = WC_Data_Store::load( 'subscription' )->get_order_type( $the_subscription );
	$subscription_type_data = wc_get_order_type( $subscription_type );

	if ( $subscription_type_data ) {
		$classname = $subscription_type_data['class_name'];
	} else {
		$classname = false;
	}

	/**
	 * Backwards compatibility: Filter classname so that the class can be overridden if extended.
	 *
	 * @param $classname         Subscription classname.
	 * @param $subscription_type Subscription type.
	 * @param $the_subscription  Subscription ID.
	 */
	$classname = apply_filters( 'woocommerce_order_class', $classname, $subscription_type, $the_subscription );

	if ( class_exists( $classname ) ) {
		$subscription = new $classname( $the_subscription );
	}

	if ( ! wcs_is_subscription( $subscription ) ) {
		$subscription = false;
	}

	return apply_filters( 'wcs_get_subscription', $subscription );
}
```

This works but not sure if we want to go with something more like option 1.

**Comment by mattallan** [comment]
Now that we're support Subscriptions in the new Custom Order Tables (now named High-Performance Order Storage/HPOS), we should no longer need to refactor the `wcs_get_subscription()` function and should be able to continue using the Order Factory.

I'll keep this issue open until we have supported the migration of Subscriptions to HPOS so we can then confirm that we don't need to refactor this function
