### ISSUE TITLE
Using wc_get_order() with a subscription ID doesn't work when Custom Order Tables are enabled (Unable to purchase Subscription with WCPay)

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#187]
## Describe the bug

After enabling COT on your store and trying to purchase a subscription with WooCommerce Payments, there's a fatal error that occurs on the checkout:

```
PHP Fatal error:  Uncaught Error: Call to a member function get_payment_tokens() on bool in /Users/matt/local/woo/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php:1478
Stack trace:
#0 /Users/matt/local/woo/wp-content/plugins/woocommerce-payments/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php(678): WC_Payment_Gateway_WCPay->get_payment_token(false)
#1 /Users/matt/local/woo/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php(2530): WC_Payment_Gateway_WCPay->maybe_schedule_subscription_order_tracking(213, false)
#2 /Users/matt/local/woo/wp-includes/class-wp-hook.php(307): WC_Payment_Gateway_WCPay->schedule_order_tracking(213)
#3 /Users/matt/local/woo/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /Users/matt/local/woo/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#5 /Users/matt/local/woo/wp-content/plugins/woocommerce-subscriptions-core/includes/data-stores/class-wcs-subscription-data-store-cpt.php in /Users/matt/local/woo/wp-content/plugins/woocommerce-payments/includes/class-wc-payment-gateway-wcpay.php on line 1478
```

This error is caused by [this line](https://github.com/Automattic/woocommerce-payments/blob/5615b8854175b81f580a905159f2225884b73e59/includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php#L675) in WooCommerce Payments which is calling `wc_get_order( $order_id )` where Order ID is actually a Subscription ID.

The reason this is failing is because subscriptions are staying in the WP Posts table and when the COT feature is enabled, the new `OrderTablesDataStore` data store is loaded and so using `wc_get_order()` can't find the order type of a subscriptionID that isn't in the COT.

### Possible Solution?
One workaround I'm thinking is we could filter `woocommerce_order_class` and check if the `$order_type` arg is empty and that `$order_id` is a subscription post ID. If it is then return 'WC_Subscription' classname which should fix these issues

## To Reproduce

1. Checkout the latest WooCommerce cot-branch and build it
2. Enable the COT feature by using the following custom code:
```
function enable_cot(){
   $order_controller = wc_get_container()
       ->get('Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController');
   if( isset( $order_controller ) ) {
       $order_controller->show_feature();
   }
}
add_action( 'init', 'enable_cot', 99 );
```
4. Go into **WooCommerce > Status > Tools** and run the Create Order Tables tool
5. Go into **WooCommerce > Settings > Advanced > Custom Data Stores**
6. Make sure "Use the WooCommerce orders tables" is enabled
   1. You will need to sync order data to custom tables to enabled this the first time by checking  "Keep the posts table and the orders tables synchronized"
7. Try to purchase a subscription on the checkout with WC Payments

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by mattallan** [comment]
> Possible Solution?

I decided to try out this possible solution and I can confirm it fixes this issue. Here's the code I used to test this solution:

```
function wcs_filter_order_class_for_cot( $classname, $order_type, $order_id ) {

	// if classname and order tyep, wasn't found and COT is enabled
	if ( empty( $classname ) && empty( $order_type ) && true ) { // replace try with COT enabled check
		$order_type      = WC_Data_Store::load( 'subscription' )->get_order_type( $order_id );
		$order_type_data = wc_get_order_type( $order_type );

		if ( 'shop_subscription' === $order_type && $order_type_data ) {
			$classname = $order_type_data['class_name'];
		}
	}

	return $classname;
}
add_filter( 'woocommerce_order_class', 'wcs_filter_order_class_for_cot', 10, 3 );
```

I suspect we might want to have a new custom-order-tables-compatibility class to house some of these workarounds as well as helper functions like checking if COT is enabled

**Comment by mattallan** [comment]
This issue has been resolved with https://github.com/Automattic/woocommerce-subscriptions-core/pull/224.

With HPOS enabled, Subscriptions and Orders are stored in the same DB so being able to call `wc_get_order( $subscription_id )` now works again.
