### ISSUE TITLE
Build error when using the current Node LTS v18

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-subscriptions-core#230]
## Describe the bug

The Long Term Support (LTS) version of Node.js is now **18.x**. [source](https://nodejs.org/en/blog/release/v18.12.0/)

Currently, when running on node v18, `npm run build` results in the error below.

```
wp-scripts build assets/src/js/index.js

node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
```

We support the LTS version of node in `.nvmrc`, so we should ensure that our dev tooling works with the new LTS version.

https://github.com/Automattic/woocommerce-subscriptions-core/blob/8017438f8e0cfc16494344f783fb134f77284d58/.nvmrc#L1

## To Reproduce

1. Checkout `trunk`
2. Install the latest LTS version of node by running `nvm install` from this repo's directory.
3. Run `nvm use`, you should now be using Node v18.x.
4. Run `npm install`. Notice an `Unsupported engine` warning.
   ```
   npm WARN EBADENGINE Unsupported engine {
   npm WARN EBADENGINE   package: 'woocommerce-subscriptions-core@2.3.0',
   npm WARN EBADENGINE   required: { node: '^16.17.1', npm: '^8.15.0' },
   npm WARN EBADENGINE   current: { node: 'v18.12.0', npm: '8.19.2' }
   npm WARN EBADENGINE }
   ```
5. Run `npm run build`. Notice the `wp-scripts` error as mentioned above.

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? no
- [x] Does this issue affect WooCommerce Payments? no

**Comment by peterfabian** [comment]
...and it also fails with current lts (v20)

```
woocommerce-subscriptions-core/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/loader-runner/lib/LoaderRunner.js:182:20
    at context.callback (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/thread-loader/dist/index.js:46:7)
    at done (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/neo-async/async.js:8069:18)
    at callback (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/thread-loader/dist/WorkerPool.js:178:19)
    at /Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/thread-loader/dist/WorkerPool.js:204:15
    at mapSeries (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at /Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/thread-loader/dist/WorkerPool.js:152:14
    at Socket.onChunk (/Users/peter/Documents/GitHub/Automattic/woocommerce-subscriptions-core/node_modules/thread-loader/dist/readBuffer.js:36:9)
    at Socket.emit (node:events:519:28)
    at Readable.read (node:internal/streams/readable:780:10)
    at Socket.read (node:net:773:39)
    at flow (node:internal/streams/readable:1281:53)
    at emitReadable_ (node:internal/streams/readable:845:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.16.0
```
