### ISSUE TITLE
Subscription renewal fails (on specific merchant site) due to fatal error when copying order items

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-subscriptions-core#308]
## Describe the bug
In 5699711-zen the user reports that scheduled actions are failing b/c of this error:

```
11-15-2022 @ 00:18:16 - scheduled action 37008 (subscription payment) failed to finish processing due to the following error: Uncaught Error: Call to a member function set_props() on bool in /var/www/wptbox/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-order-functions.php:743
Stack trace:
#0 /var/www/wptbox/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-order-functions.php(261): wcs_copy_order_item()
#1 /var/www/wptbox/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-renewal-functions.php(29): wcs_create_order_from_subscription()
#2 /var/www/wptbox/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-manager.php(116): wcs_create_renewal_order()
#3 /var/www/wptbox/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-manager.php(89): WC_Subscriptions_Manager::process_renewal()
#4 /var/www/wptbox/wp-includes/class-wp-hook.php(308): WC_Subscriptions_Manager::prepare_renew
11-15-2022 @ 00:18:16 - action args: subscription_id: 21762
```

## To Reproduce

I'm not sure what conditions exist on their server/site to cause this, but it happens on subscription renewal as well as when trying to create a new subscription or using subscription actions menu to process renewal. It's probably worth mentioning that the problem doesn't happen at all with the same data set on a test site of mine, i.e. I don't believe this is caused by a missing database record.

### Expected behavior

For the subscription to renew.
### Actual behavior

~~It seems that b/c `&$to_item` is passed by reference it somehow ends up null.~~~~https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/wcs-order-functions.php#L740~~

~~I cowboy edited the file on their site and cleared up the problem.~~

edit: I didn't clear up the problem. My testing was inconsistent :(

## Product impact

- [ x] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Probably Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by WillBrubaker** [comment]
Found another report of this in 5743857-zen

**Comment by haszari** [comment]
Next step here is to reproduce the issue on a minimal setup – latest WooCommerce + WC Subscriptions (or WCPay if it's reproducible there).

If it's reproducible we can look at prioritising a fix. 

@WillBrubaker I've updated the title to clarify the impact - what's broken, for who - please feel free to refine.

**Comment by haszari** [comment]
The error is referring to this line in `wcs_copy_order_item()`. The `$to_item` passed into the function is a boolean, it should be a `WC_Order_Item`.

https://github.com/Automattic/woocommerce-subscriptions-core/blob/5.0.0/includes/wcs-order-functions.php#L740-L751

We have recently changed this code (`subscriptions-core` library version 5.1), though it hasn't yet shipped in WC Subscriptions. So the issue might not be reproducible with WC Subscriptions.

@WillBrubaker I'm assuming this is using the latest WC Subscriptions – is that correct? Any other plugins or customisations on the affected stores?

**Comment by WillBrubaker** [comment]
yes, subs is up to date. yes, there are other plugins but I don't know how they might affect the stores.

**Comment by james-allan** [comment]
For some extra context, the error feeds in from here:

https://github.com/Automattic/woocommerce-subscriptions-core/blob/121ef4b833aa9ae47e91e22389fca8d30057deba/includes/wcs-order-functions.php#L197-L204

As you can see from the code above, we call `wc_add_order_item()` to add a new item to an order. That function returns a order item ID so we then call `get_item()` to fetch the newly created item. The issue here is that the newly created item isn't being returned or is failing to be loaded (returning `null`) and that causes our later code to fail. 

**A suggestion**:

Instead of creating an order item, getting an ID and relying on it returning the object via the ID we could tighten this code and remove the reliance on fetching the order item. 

For example, we could use objects from the get go: 


```php
// Could be switch or a type => class array.
switch ( $item->get_type() ) {
	case 'line_item':
	case 'product':
		$classname = 'WC_Order_Item_Product';
		break;
...

$order_item = new $classname();
$order_item->set_order_id( $order_id )

wcs_copy_order_item( $item, $order_item ); 
```

The goal would be a little more defensive code and remove the reliance on having to successfully get the order item instance from the DB.

**Comment by barryhughes** [comment]
Subscriptions Core has now been archived. For more information, please [refer to this announcement](https://developer.woocommerce.com/2025/05/06/developer-advisory-subscriptions-core-code-moving-into-woocommerce-subscriptions-plugin/).
