### ISSUE TITLE
Deleting a subscription with validation error causes PHP error

### ISSUE THREAD

**Issue by darrylhein** [Automattic/woocommerce-subscriptions-core#533]
## Describe the bug
I tried to delete (move to trash) a subscription, but because it had validation error, all I received as the critical error message.

The critical error message I received via email was:

```
An error of type E_ERROR was caused in line 2470 of the file /wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscription.php. 
Error message: Uncaught Exception: Subscription #58154: The cancelled date must occur after the last payment date. The end date must occur after the last payment date. in /wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscription.php:2470
Stack trace:
#0 /wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscription.php(1272): WC_Subscription->validate_date_updates()
#1 /wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscription.php(526): WC_Subscription->update_dates()
#2 /wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wc-subscriptions-manager.php(917): WC_Subscription->update_status()
...[remainder not sent]
```

## To Reproduce
I don't actually know how to get the subscription into the invalid state.

### Expected behavior
I would expect that you'd still be able to delete the subscription or at least receive an error message showing what's actually wrong.

### Actual behavior
Received the critical error message.

## Product impact
I believe this is only on woo subscriptions.

- [x] Does this issue affect WooCommerce Subscriptions? yes
- [ ] Does this issue affect WooCommerce Payments? no

**Comment by 10goC** [comment]
Ran into this bug recently.
There's a switch statement on that line that's missing the break statements in all cases.
Adding them solves the issue.

**Comment by barryhughes** [comment]
Interestingly, I just hit a variant of this problem, and it's sufficiently similar that I think it makes sense to add a note here, rather than create a new issue. So, *essentially,* the same problem can be replicated using code looking like this (of course, you'd need to supply a valid subscription ID):

```php
$subscription = wc_get_subscription( $subscription_id );
$subscription->set_end_date( '2030-01-01' ); # Expected format is actually 'Y-m-d H:i:s'
$subscription->save();
```

Upon save, if for instance you run this via WP CLI, you will see an exception:

```
Exception caught in get_order. Invalid end date. The date must be of the format: "Y-m-d H:i:s".
```

The problem is that, despite an exception being thrown, the invalid date was accepted and was committed to the database. Consequently, if one makes this mistake, the impacted subscription cannot be loaded without this exception being raised. Amongst other side-effects, this means that the main subscriptions view (**WooCommerce ‣ Subscriptions**) will not load—it will instead "crash" because of the uncaught exception.

Important detail: the exception itself is actually thrown when the [order record is initialized](https://github.com/Automattic/woocommerce-subscriptions-core/blob/7.9.0/includes/data-stores/class-wcs-orders-table-subscription-data-store.php#L632). The reason we also see this following a `save()` operation is that, within this process, a [fresh copy](https://github.com/woocommerce/woocommerce/blob/9.5.2/plugins/woocommerce/src/Internal/DataStores/Orders/OrdersTableDataStore.php#L2891) of the order object is created and re-initialized (or, at least, this is true if HPOS is enabled). Thoughts:

- In the context of the **WooCommerce ‣ Subscriptions** list view, if we encounter bad data like this it's probably better to skip the problematic subscription (and perhaps render some sort of inline error) rather than crash the entire page.
- If a date like `2030-01-01` is invalid (though the same principal can be applied to various properties), then it probably shouldn't be accepted at all. Further thoughts on this:
    - As described, we already throw an exception upon calling `$subscription->save()` ... the problem is that, by the time this happens, the change has already been committed to the database. Perhaps we could move our validation checks to an earlier point in this operation.
    - It might be better if `$subscription->set_end_date()` returned a bool to indicate success or failure, and also would be good if it logs an error or emits a *doing-it-wrong* and, finally, in these cases, it simply should not accept the change.

**Comment by barryhughes** [comment]
Further note: recovering from this problem requires manually updating the relevant DB record (or, to resolve things programmatically, one would need to work with `$wpdb` directly, etc) simply because the exception is raised when you next try to load/create the subscription object, which blocks the use of standard CRUD methods supplied by `WC_Subscription`/`WC_Order` for this task.

**Comment by barryhughes** [comment]
Subscriptions Core has now been archived. For more information, please [refer to this announcement](https://developer.woocommerce.com/2025/05/06/developer-advisory-subscriptions-core-code-moving-into-woocommerce-subscriptions-plugin/).
